### ISSUE TITLE
Unable to execute on Ubuntu 17.04

### ISSUE THREAD

**Issue by qnm** [brwyatt/puppet-flatpak#1]
Running flatpak using `puppet 4.10.8` on `ubuntu 17.04` I see the following error:

`Error: Evaluation Error: Operator '[]' is not applicable to an Undef Value. at /home/qnm/github/qnm/boxen/modules/flatpak/manifests/init.pp:55:17 on node glenlivet`

This seems to be due to `facter` not supplying the codename in the form the code expects.

My facter returns this for `os`:

`os => {"name"=>"Ubuntu", "family"=>"Debian", "release"=>{"major"=>"17.04", "full"=>"17.04"}, "lsb"=>{"distcodename"=>"zesty", "distid"=>"Ubuntu", "distdescription"=>"Ubuntu 17.04", "distrelease"=>"17.04", "majdistrelease"=>"17.04"}}`

A small modification to line 55 to read the codename using `$::os['lsb']['distcodename']` allowed the module to execute.

I'd submit a PR but there's obviously a reason your code works for you - so hopefully we can resolve this for both of us!

**Comment by brwyatt** [comment]
Interesting, I'm using `puppet 4.10.8` myself (but on `ubuntu 16.04`), but do not have `::os['lsb']`. I think I can find a way to make both work, though.

**Comment by brwyatt** [comment]
After doing more research, it looks like this might be a difference between the `2.x` versions of Facter and the `3.x` versions.

https://docs.puppet.com/facter/2.3/core_facts.html#os
https://docs.puppet.com/facter/latest/core_facts.html#os

**Comment by brwyatt** [comment]
Give the `issues/1` branch (PR #3) a try and see if that resolves the issue you were seeing.

**Comment by brwyatt** [comment]
I'm having difficulty testing this on my end. I cannot get Puppet 4.10 to use Facter 2.4, it seems that since Puppet 4.2's switch to cfacter, this shouldn't be a possible situation (at least not with Puppet Apply). Since parameter type declarations are new to Puppet 4, I'm also unable to test this fully on Puppet 3.8 with Facter 2.4.

That being said, I tested the logic added on Puppet 3.8 and Facter 2.4, and was able to confirm it results with the expected value, and have tested the full changes on Puppet 4.10 with Facter 3.6, so I'm thinking the fix in #3 should be safe to merge.
